server:
    port: 2020
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://rm-8vba9a2q811ql3v04po.mysql.zhangbei.rds.aliyuncs.com:3306/gmall-pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: xxt
            password: 999piyanning
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
    cloud:
        nacos:
            discovery:
                server-addr: 121.89.196.196:8848
    application:
        name: gmall-product


#mybatis
mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.xxt.gmall.product.entity
    global-config:
        #数据库相关配置
        db-config:
            #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: AUTO
            logic-delete-value: 1
            logic-not-delete-value: 0
        banner: false
    #原生配置
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'

logging:
    level:
        com.xxt.gmall: debug
